{{ if (include "authelia.enabled.ingress.traefik.tlsOption" .) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "authelia.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.ingress.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.ingress.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  minVersion: {{ default "VersionTLS12" .Values.ingress.traefikCRD.tls.options.minVersion }}
  maxVersion: {{ default "VersionTLS13" .Values.ingress.traefikCRD.tls.options.maxVersion }}
  {{- with $prefernces := .Values.ingress.traefikCRD.tls.options.curvePreferences }}
  curvePreferences: {{ toYaml $prefernces | nindent 4 }}
  {{- end }}
  {{- with $suites := default (list "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" "TLS_RSA_WITH_AES_256_GCM_SHA384") .Values.ingress.traefikCRD.tls.options.cipherSuites }}
  cipherSuites: {{ toYaml $suites | nindent 4 }}
  {{- end }}
  {{ with $strict := .Values.ingress.traefikCRD.tls.options.sniStrict }}
  sniStrict: {{ $strict }}
  {{- end }}
{{- end -}}