apiVersion: v2
name: authelia
version: 0.1.0
kubeVersion: 
description: Authelia Experimental Chart
type: application
keywords: []
home: https://www.authelia.com
sources:
  - https://www.github.com/authelia/chartrepo/charts/experimental/
  - https://www.github.com/authelia/authelia
dependencies: []
maintainers:
  - name:  Cl√©ment Michaud
    url: https://github.com/clems4ever
  - name: James Elliott
    url: https://github.com/james-d-elliott
  - name: Amir Zarrinkafsh
    url: https://github.com/nightah
icon: https://avatars2.githubusercontent.com/u/59122411?s=200&v=4
appVersion: 4.24.1
deprecated: false
annotations:
  alpha: true